config/routes.rb
Rails.application.routes.draw do
  root :to => 'base#index'
  devise_for :users
  # devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' , passwords: 'users/passwords', two_factor_authentication: 'users/two_factor_authentication', unlocks: 'users/unlocks',password_expired: 'users/password_expired'}

  devise_scope :user do
    authenticated :user do
      root 'base#index', as: :authenticated_root
    end

    # unauthenticated do
    #   root 'devise/sessions#new', as: :unauthenticated_root
    # end
    post "sign_up", to: "registrations#create"
    post "sign_in", to: "sessions#create"

    resources :papers  do
      collection do
        get :questions
        get :solve_paper
        get :view_questions
        post :submit_paper
        resources :students do
          collection do
            get :questions
            get :solve_paper
            post :submit_paper
            get :student_paper
            get :view_paper
          end
        end
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!, except: [:create]
  layout 'application'

  def new
    @user=User.new
  end

  def index
    @users=User.student
  end
  def update
    @user=User.where(id:params[:id]).try(:first)
    if @user.present? && @user.is_block?
      @user.update(is_block:false)
      flash[:sucess]='User Blocked succesfully'
    else
      @user.update(is_block:true) if @user.present?
      flash[:sucess]='User is Un-Blocked'
    end
    redirect_back(fallback_location: root_path)
  end
  def create
    @user=User.new(new_student_params)
    @user.role='student'
    if @user.save
      flash[:sucess]='User Saved succesfully'
    else
      flash[:sucess]='User not saved succesfully'
    end
    redirect_to students_url
  end

  def student_paper
    if params[:id].present?
      count= UserAnswer.where(user_id:params[:id]).pluck(:paper_id).try(:uniq)
      @papers=Paper.where(id:count)
    end
  end

  def view_paper
    @paper=Paper.where(id:params[:paper_id]).try(:first)
  end

  private
  def new_student_params
    params.require(:user).permit(:email,:password)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/index.html.erb
<style>
  #gatetable{
      margin-bottom: 20%;
      margin-top: 5%;
  }
</style>
<table id="gatetable" class="table table-bordered table-striped text-align-center-app-config">
  <thead class="datatable-thead-app-config">
  <th>Email</th>
  <th>Student's Status</th>
  <th>Edit</th>
  <th>Total Papers</th>

  <!--      <th>MTD Vol</th>-->
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%=user.email %></td>
      <td><%=user.is_block? ? 'Active' : 'Not Active'  %></td>
      <td>
        <%= link_to student_path(id: user.id), method: :patch ,'data-original-title':'Detail', class: 'cutom_tootltip pull-right detail-btn' do %>
          <%=user.is_block? ? 'Block This User' : 'UnBlock this User'  %>

        <% end %>

      </td>
      <td>
        <%count= UserAnswer.where(user_id:user.id).pluck(:paper_id).try(:uniq) %>

        <% if count.present? %>
        <%= link_to student_paper_students_path(id: user.id), method: :get ,'data-original-title':'Detail', class: 'cutom_tootltip pull-right detail-btn' do %>
            <%= count.try(:count) %>
        <% end %>
        <% else %>
          <%= count.try(:count) %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>

</table>

app/views/students/new.html.erb
<%#= form_for(@user) do |f| %>
<%#=f.simple_fields_for :user, User.new do |f| %>
<%#= simple_form_for @user , url: students_path , method: :post  do |f| %>
<style>
  .nifty_form{
      margin-bottom: 20%;
  }
</style>
<%= form_with model: @user,url: students_path, class: "nifty_form" do |f| %>

  <div class="buyrate-row">
    <h3 id="buyrate-info-heading" class="header-color">Create Student</h3><br>
    <div class="col-md-1"></div>
    <div class="col-md-10" id="buyrate-user-fields-container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="form-group col-md-6">
              <%= f.label :email, "Email", class: 'control-label' %>
              <%= f.text_field :email, class: "form-control input-lg", :size => "48",  placeholder: 'Student Email' %>
              <div class="help-block with-errors"></div>
            </div>
            <div class="col-md-1"></div>
            <div class="form-group col-md-5">
              <%= f.label :password, "Password", class: 'control-label' %>
              <%= f.text_field :password, id: 'tx', class: "form-control input-lg", :size => "48", placeholder: 'Password' %>
              <div id='tx-error' class="help-block with-errors"></div>
              <div id="tx-error" class="has-error"></div>
            </div>
            <div class="form-group col-md-5">
             <input type="submit" class="btn btn-primary">
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/students/student_paper.html.erb
<style>
    #gatetable{
        margin-bottom: 20%;
        margin-top: 5%;
    }
</style>
<table id="gatetable" class="table table-bordered table-striped text-align-center-app-config">
  <thead class="datatable-thead-app-config">
  <th>Subject</th>
  <th>Total Questions</th>
  <th>Right Answers</th>
  <th>View Paper</th>

  <!--      <th>MTD Vol</th>-->
  </thead>

  <tbody>
  <%  if @papers.present? %>
  <% @papers.each do |paper| %>
    <tr>
      <td><%=paper.subject %></td>
      <td><%=paper.try(:questions).try(:count) %></td>
      <% count=UserAnswer.where(user_id:params[:id],paper_id:paper.id,is_correct: true) %>
      <td>
        <%= count.try(:count) %>
      </td>
      <td>
        <%#count= UserAnswer.where(user_id:user.id).pluck(:paper_id).try(:uniq) %>

          <%= link_to view_paper_students_path(paper_id: paper.id,user_id:params[:id]), method: :get ,'data-original-title':'Detail', class: 'cutom_tootltip pull-right detail-btn' do %>
            View Paper
          <% end %>
      </td>
    </tr>
  <% end %>
    <% end %>
  </tbody>

</table>

app/views/students/view_paper.html.erb
<div class="container">
  <% @paper.try(:questions).each do |question| %>
  <div class="row">
  <p>   <span class="font-weight-bold">Question: </span><%=question.name %></p><br>
  </div>
    <div class="row">
    <p>
      <span class="font-weight-bold">Correct Option: </span>
      <%answer= UserAnswer.where(user_id:params[:user_id],question_id:question.id,paper_id:@paper.id).try(:first) %>
      <%=question.try(:multiple_choice).try(:correct_option) %>
    </p><br>
    </div>
    <div class="row">
    <p>
      <span class="font-weight-bold">Option Choosen: </span>
      <%=answer.try(:selected_option) || '--' %>
    </p><br>
    </div>
    <div class="row">
    <p>
      <span class="font-weight-bold">Answer </span>
      <%=answer.try(:is_correct?) ? 'True' : 'False' %>
    </p><br>
  </div>
    <% end %>

</div>