config/routes.rb
Rails.application.routes.draw do
  root :to => 'base#index'
  devise_for :users
  # devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' , passwords: 'users/passwords', two_factor_authentication: 'users/two_factor_authentication', unlocks: 'users/unlocks',password_expired: 'users/password_expired'}

  devise_scope :user do
    authenticated :user do
      root 'base#index', as: :authenticated_root
    end

    # unauthenticated do
    #   root 'devise/sessions#new', as: :unauthenticated_root
    # end
    post "sign_up", to: "registrations#create"
    post "sign_in", to: "sessions#create"

    resources :papers  do
      collection do
        get :questions
        get :solve_paper
        get :view_questions
        post :submit_paper
        resources :students do
          collection do
            get :questions
            get :solve_paper
            post :submit_paper
            get :student_paper
            get :view_paper
          end
        end
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_admin_header.html.erb
<section id="hero">
  <div class="hero-container">
    <div id="heroCarousel" class="carousel slide carousel-fade" data-ride="carousel">

      <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

      <div class="carousel-inner" role="listbox">

        <!-- Slide 1 -->
        <div class="carousel-item active">
          <div class="carousel-background">
            <%= image_tag "img/slide/11.jpg" %>
<!--            <img src="assets/img/slide/11.jpg" alt="">-->
          </div>
          <div class="carousel-container">
            <div class="carousel-content">
              <h2 class="animate__animated animate__fadeInDown">Welcome to <span>Ikram Forces Academy</span></h2>
              <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
              <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Get Started</a>
            </div>
          </div>
        </div>

        <!-- Slide 2 -->
        <div class="carousel-item">
          <div class="carousel-background">
          <%= image_tag "img/slide/22.jpg" %>
<!--            <img src="assets/img/slide/22.jpg" alt="">-->
          </div>
          <div class="carousel-container">
            <div class="carousel-content">
              <h2 class="animate__animated animate__fadeInDown">Welcome to Ikram Forces Academy</h2>
              <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
              <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Get Started</a>
            </div>
          </div>
        </div>

        <!-- Slide 3 -->
        <div class="carousel-item">
          <div class="carousel-background"><%= image_tag "img/slide/44.jpg" %>
<!--            <img src="assets/img/slide/44.jpg" alt="">-->
          </div>
          <div class="carousel-container">
            <div class="carousel-content">
              <h2 class="animate__animated animate__fadeInDown">Love Your Armed Forces</h2>
              <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
              <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Get Started</a>
            </div>
          </div>
        </div>

      </div>

      <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon icofont-thin-double-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

      <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon icofont-thin-double-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

    </div>
  </div>
</section><!-- End Hero -->

<!-- ======= Header ======= -->
<header id="header">
  <div class="container d-flex">

    <div class="logo mr-auto">
      <h1 class="text-light"><a href="index.html"><span>Shuffle</span></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
    </div>

    <nav class="nav-menu d-none d-lg-block">
      <ul>
        <li class="active"><a href=<%= root_path %>>Home</a></li>
        <li><a href="#about">About Us</a></li>
        <li><a href="#services">Services</a></li>
        <% if user_signed_in?%>
<!--      <li><a href=<%#= new_user_session_path %>>User Sign In</a></li>-->

        <li><a href=<%= papers_path %>>Test</a></li>
        <% end %>

        <li class="drop-down"><a href="">Drop Down</a>
          <ul>
            <% if user_signed_in? && current_user.admin?%>
            <li><a href=<%= new_student_path %>>Create Student</a></li>
            <% end %>
            <li class="drop-down"><a href="#">Students</a>
              <ul>
                <li><a href=<%= new_user_session_path %>>User Sign In</a></li>
                <% if user_signed_in? && current_user.admin?%>
                <li><a href=<%= students_path %>>Students</a></li>
                <% end %>
              </ul>
            </li>
<!--            <li><a href=<%#= students_path %>>Students</a></li>-->
<!--            <li><a href="#">Drop Down 4</a></li>-->
<li>
            <% if current_user %>
              <%= link_to destroy_user_session_path, :method => :delete,:data => { :confirm => 'Logout?'} do  %>
               Sign Out
              <% end %>
            <% end %>
</li>
<!--            <li><a href=<%#=destroy_user_session_path %>>Sign Out</a></li>-->
          </ul>
        </li>
        <li><a href="#contact">Contact Us</a></li>

      </ul>
    </nav><!-- .nav-menu -->

  </div>
</header><!-- End Header -->

app/views/shared/_admin_sidebar.html.erb
<!-- The sidebar -->
<div class="sidebar">
  <a class="active" href=<%=  papers_path %>>Papers</a>
  <a href=<%=  papers_path %>>News</a>
  <a href=<%=  papers_path %>>Contact</a>
  <a href=<%=  papers_path %>>About</a>
</div>

<!-- Page content -->
<div class="content">
  ..
</div>

app/views/shared/_flash.html.erb
<style>
  .notice{
      font-size: 26px;
      color: green;
  }
</style>
<% flash.each do |key, value| %>
  <p class="notice"><%= value %></p>
<!--  <p class="alert"><%#= alert %></p>-->
<%end%>

app/views/shared/_footer.html.erb
<footer id="footer">
  <div class="footer-top">
    <div class="container">
      <div class="row">

        <div class="col-lg-3 col-md-6 footer-info">
          <h3>Shuffle</h3>
          <p>
            A108 Adam Street <br>
            NY 535022, USA<br><br>
            <strong>Phone:</strong> +1 5589 55488 55<br>
            <strong>Email:</strong> info@example.com<br>
          </p>
          <div class="social-links mt-3">
            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
          </div>
        </div>

        <div class="col-lg-2 col-md-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
          </ul>
        </div>

        <div class="col-lg-4 col-md-6 footer-newsletter">
          <h4>Our Newsletter</h4>
          <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
          <form action="" method="post">
            <input type="email" name="email"><input type="submit" value="Subscribe">
          </form>

        </div>

      </div>
    </div>
  </div>

  <div class="container">
    <div class="copyright">
      &copy; Copyright <strong><span>Shuffle</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/bootstrap-3-one-page-template-free-shuffle/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </div>
</footer>