config/routes.rb
Rails.application.routes.draw do
  root :to => 'base#index'
  devise_for :users
  # devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' , passwords: 'users/passwords', two_factor_authentication: 'users/two_factor_authentication', unlocks: 'users/unlocks',password_expired: 'users/password_expired'}

  devise_scope :user do
    authenticated :user do
      root 'base#index', as: :authenticated_root
    end

    # unauthenticated do
    #   root 'devise/sessions#new', as: :unauthenticated_root
    # end
    post "sign_up", to: "registrations#create"
    post "sign_in", to: "sessions#create"

    resources :papers  do
      collection do
        get :questions
        get :solve_paper
        get :view_questions
        post :submit_paper
        resources :students do
          collection do
            get :questions
            get :solve_paper
            post :submit_paper
            get :student_paper
            get :view_paper
          end
        end
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/paper.rb
class Paper < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :questions
  has_many :user_answers, :through => :questions, foreign_key: :paper_id
  accepts_nested_attributes_for :questions
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :authenticate_user!, except: [:create]
  def index

  end

  def new
    @paper=Paper.new
  end

  def index
    @papers=Paper.all.order('id DESC')
  end

  def questions
    @papers=Paper.all
  end

  def solve_paper
    @paper=Paper.where(id:params[:id]).try(:first)
  end

  def submit_paper
    user=User.where(id:params[:user_id]).try(:first)
    if params[:paper_id].present?
      paper=Paper.where(id:params[:paper_id]).try(:first)
      ids=paper.questions.pluck(:id)
      ids.each do |q|
        if params["question_#{q}"].present?
          question=Question.includes(:multiple_choice).where(id:q).try(:first)
          multiple_choice=question.multiple_choice
          # question=MultipleChoice.where(id:q).try(:first)
          if params["question_#{q}"]['answer'].present?
            user_answer=UserAnswer.new(user_id:user.id)
            user_answer.question_id=question.id
            user_answer.paper_id=paper.id
            user_answer.selected_option=params["question_#{q}"]['answer']
            if multiple_choice.correct_option==params["question_#{q}"]['answer']
              user_answer.is_correct=true
            end
            user_answer.save
          end
        end
      end
      count=UserAnswer.where(user_id:params[:user_id],paper_id:params[:paper_id],is_correct: true).try(:count)
      flash[:successs]="Total Right Answers are #{count}"

    end
    redirect_to root_path
  end
  def create
    @paper=Paper.new(new_paper_params)
    @paper.save
    if params[:questions].present?
      questions=[]
      params[:questions].keys.each do |obj|
        @question=Question.new(new_question_params(params[:questions]["#{obj}"]))
        @question.paper_id=@paper.id
        # params[:multiple_choices]["#{obj}"]['question_id']=@question.id
        questions.push(@question)
      end
      questions=Question.import questions
    end
    if params[:multiple_choices].present? && questions.present?
      multiple_choices=[]
      params[:multiple_choices].keys.each do |obj|
        @multiple_choices=MultipleChoice.new(new_multiple_params(params[:multiple_choices]["#{obj}"]))
        @multiple_choices.question_id=questions.ids[obj.try(:to_i)]
        # @multiple_choices.paper_id=params[:questions]["#{obj}"].id
        # @multiple_choices.save
        multiple_choices.push(@multiple_choices)
      end
      choices=MultipleChoice.import multiple_choices
    end
    redirect_back(fallback_location: root_path)
  end

  def view_questions
    @paper=Paper.where(id:params[:paper_id]).try(:first)
  end

  def edit
    @paper=Paper.where(id:params[:id]).try(:first)
  end

  def update
    @paper=Paper.where(id:params[:paper_id]).try(:first)
    @paper.subject=params[:paper]['subject']
    @paper.time=params[:paper]['time']
    @paper.save
    if params[:questions].present?
      questions=[]
      questionss=[]
      params[:questions].keys.each do |obj|
        @question=Question.where(id:params[:questions]["#{obj}"]['id']).try(:first)
        if @question.present?
          @question.name=params[:questions]["#{obj}"]['name']
          questions.push(@question)
        else
          @question=Question.new(new_question_params(params[:questions]["#{obj}"]))
          @question.paper_id=@paper.id
          questions.push(@question)
        end
        # params[:multiple_choices]["#{obj}"]['question_id']=@question.id
      end
      # BlockTransaction.import block_transactions, on_duplicate_key_update: {conflict_target: [:sequence_id], columns: [:updated_at, :tx_amount, :net_fee, :total_net, :privacy_fee, :fee_in_cents, :amount_in_cents]}
      if questions.present?
        questions=Question.import questions , on_duplicate_key_update: {conflict_target: [:id], columns: [:name]}
      end
    end
    if params[:multiple_choices].present? && questions.present?
      multiple_choices=[]
      params[:multiple_choices].keys.each do |obj|
        @multiple_choices=MultipleChoice.where(id:params[:multiple_choices]["#{obj}"]['id']).try(:first)
        if @multiple_choices.present?
          # @multiple_choices=MultipleChoice.new(new_multiple_params(params[:multiple_choices]["#{obj}"]))
          @multiple_choices.option_a=params[:multiple_choices]["#{obj}"]['option_a']
          @multiple_choices.option_b=params[:multiple_choices]["#{obj}"]['option_b']
          @multiple_choices.option_c=params[:multiple_choices]["#{obj}"]['option_c']
          @multiple_choices.option_d=params[:multiple_choices]["#{obj}"]['option_d']
          @multiple_choices.option_e=params[:multiple_choices]["#{obj}"]['option_e']
          @multiple_choices.correct_option=params[:multiple_choices]["#{obj}"]['correct_option']
          multiple_choices.push(@multiple_choices)
        else
          @multiple_choices=MultipleChoice.new(new_multiple_params(params[:multiple_choices]["#{obj}"]))
          @multiple_choices.question_id=questions.ids[obj.try(:to_i)]

          multiple_choices.push(@multiple_choices)
          # @multiple_choices.question_id=@paper.id
        end
        # @multiple_choices.save
      end
      # choices=MultipleChoice.import multiple_choices
      if multiple_choices.present?
        multiple_choices=MultipleChoice.import multiple_choices , on_duplicate_key_update: {conflict_target: [:id], columns: [:option_a,:option_b,:option_c,:option_d,:option_e,:correct_option]}
      end
    end
    flash[:success]='Paper is updated'
    redirect_back(fallback_location: root_path)
  end

  private
  def new_paper_params
    params.require(:paper).permit(:subject,:time)
  end
  def new_question_params(obj)
    obj.permit(:name,:paper_id)
  end

  def new_multiple_params(obj)
    # params.require(:multiple_choices).permit(:question_id,:option_a,:option_b,:option_c,:option_d,:option_e,:correct_option)
    obj.permit(:question_id,:option_a,:option_b,:option_c,:option_d,:option_e,:correct_option)
  end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/edit.html.erb
<style>
    .col-md-12{
        max-width: 95%;
    }
    .form-inline{
        margin-top: 2%;
        margin-bottom: 20%;
    }
</style>
<%= form_for @paper, url: {controller: "papers", action: "update"} do |f| %>
<%#= nested_form_for @paper,url: {controller: "papers", action: "create"}, method: :post, html: {class: "form-inline",autocomplete:"off",id:"paper_form"} do |f| %>
  <!--    , html:{id: :agentform, onsubmit:"disableButton('agentform','submit_edit_button1')"}-->

  <div class="abcd">
    <div class="col-md-12">
      <div class="row">
        <div class="form-group col-md-4">
          <label for="id">Paper Time</label>
          <%= f.text_field :time,class:"form-control" %><br>
          <label for="id">Paper Title</label>
          <%= f.text_field :subject,class:"form-control" %>
          <%#= f.hidden_field :id,class:"form-control" %>

          <input type="hidden" name='paper_id' value="<%= f.object.id %>">

        </div>


      </div>


    </div>
    <div class="col-md-12" s>
      <input type="hidden" id="total_count" value="<%= @paper.try(:questions).try(:count) %>">
      <% @paper.questions.each_with_index  do |q,i| %>
<!--      <div class="row">-->
        <div class="form-group col-md-4">
          <label for="id">Question <%= i+1 %>:</label>
          <input type="text" name='questions[<%=i %>]name' value="<%= q.name %>" class="form-control">
          <input type="hidden" name='questions[<%=i %>]id' value="<%= q.id %>" class="form-control">

        </div>
        <% multi=q.multiple_choice %>
        <% if multi.present?%>
          <div class="row">
        <div class="form-group col-md-4">
          <label for="id">Option A</label>
          <input type="text" name='multiple_choices[<%=i %>][option_a]' value="<%= multi.option_a %>" class="form-control" >
          <input type="hidden" name='multiple_choices[<%=i %>]id' value="<%= multi.id %>" class="form-control">

        </div>
        <div class="form-group col-md-4">
          <label for="id">Option B</label>
          <input type="text" name='multiple_choices[<%=i %>][option_b]' value="<%= multi.option_b %>" class="form-control">
        </div>
        <div class="form-group col-md-4">
          <label for="id">Option C</label>
          <input type="text" name='multiple_choices[<%=i %>][option_c]' value="<%= multi.option_c %>" class="form-control">
        </div>
          </div>
          <div class="row">
        <div class="form-group col-md-4">
          <label for="id">Option D</label>
          <input type="text" name='multiple_choices[<%=i %>][option_d]' value="<%= multi.option_d %>" class="form-control">
        </div>
        <div class="form-group col-md-4">
          <label for="id">Option E</label>
          <input type="text" name='multiple_choices[<%=i %>][option_e]' value="<%= multi.option_e %>" class="form-control">
        </div>
        <div class="form-group col-md-4">
          <label for="id">Correct Option</label>
          <input type="text" name='multiple_choices[<%=i %>][correct_option]' value="<%= multi.correct_option %>" class="form-control">
        </div>
          </div>

<!--      </div>-->
    <% end %>
    <% end %>

    </div>

    <!--<div class="col-md-12">-->



  </div>
  <div class="row">
    <div class="col-md-12">
      <span id="more_question">Add More Question +</span><br>
      <!--  </div>-->
    </div>
    <!-- </div>-->
    <br>
    <br>
    <!--   <div class="row">-->
    <div class="col-md-12">
      <%= submit_tag "Update" , class:'btn btn-primary' %>
    </div>
  </div>
<% end %>



<script>


    var counter=parseInt($('#total_count').val());
    counter=counter-1
    $('#more_question').on('click',function () {
        debugger
//           document.getElementById('my_file'+counter).click();
        counter=counter+1
        if(counter!=0){
            // $('.abcd').append(' <input type="text" name="paper[subject]['+counter+']"><br>'+
            //     ' <input type="text" name="questions[name]['+counter+']"><br>'+
            // ' <input type="text" name="multiple_choices[option_a]['+counter+']"><br>' +
            // '    <input type="text" name="multiple_choices[option_b]['+counter+']"><br> ' +
            // '   <input type="text" name="multiple_choices[option_c]['+counter+']"><br>' +
            // '   <input type="text" name="multiple_choices[option_d]['+counter+']"><br> ' +
            // '   <input type="text" name="multiple_choices[option_e]['+counter+']"><br> '+
            // '   <input type="text" name="multiple_choices[correct_option]['+counter+']"><br>')




            $('.abcd').append('<div class="col-md-12"><div class="row"> '+
                ' <div class="form-group col-md-4"> <label for="id">Question '+counter+'</label> <input type="text" name="questions['+counter+'][name]"> </div> <div class="form-group col-md-4"> <label for="id">Option A</label> <input type="text" name="multiple_choices['+counter+'][option_a]"> </div> <div class="form-group col-md-4"><label for="id">Option B</label> <input type="text" name="multiple_choices['+counter+'][option_b]"></div> </div>   </div> ' +
                '<div class="col-md-12"><div class="row">  '+
                ' <div class="form-group col-md-4"> <label for="id">Option C</label> <input type="text" name="multiple_choices['+counter+'][option_c]"> </div> <div class="form-group col-md-4"> <label for="id">Option D</label> <input type="text" name="multiple_choices['+counter+'][option_d]"> </div>  <div class="form-group col-md-4"><label for="id">Option E</label> <input type="text" name="multiple_choices['+counter+'][option_e]"></div> </div>   </div> '+
                '<div class="col-md-12"><div class="row"> '+
                ' <div class="form-group col-md-4"> <label for="id">Correct Option</label> <input type="text" name="multiple_choices['+counter+'][correct_option]"> </div>  </div>   </div> ');
        }

    });
</script>

app/views/papers/index.html.erb
<style>
  .test{
      margin-top: 20%;
      margin-bottom: 20%;
      font-size: 32px;
  }
</style>
<% if current_user.admin? %>
<%= link_to 'New Test' ,new_paper_path,class:'test'%>
  <% end %>

<table id="gatetable" class="table table-bordered table-striped text-align-center-app-config">
  <thead class="datatable-thead-app-config">
    <th>Paper Title</th>
  <th>Number of questions</th>
    <% unless current_user.admin?%>
  <th>Test</th>
    <% end %>
    <% if current_user.admin?%>
    <th>View Questions</th>
    <th>Edit Questions</th>
  <% end %>
  <!--      <th>MTD Vol</th>-->
  </thead>

  <tbody>
  <% @papers.each do |paper| %>
  <% paper_attempt= UserAnswer.where(user_id:current_user.id,paper_id:paper.id) %>
    <% unless paper_attempt.present? %>
  <tr>
    <td><%=paper.subject %></td>
    <td><%=paper.questions.count %></td>
    <% unless current_user.admin?%>
    <td>
      <%= link_to solve_paper_papers_path(id: paper.id),'data-original-title':'Detail', class: 'cutom_tootltip pull-right detail-btn' do %>
        Start Test

      <% end %>

    </td>
    <% end %>
    <% if current_user.admin?%>
      <td>

      <%= link_to view_questions_papers_path(paper_id: paper.id),'data-original-title':'Detail', class: 'cutom_tootltip pull-right detail-btn' do %>
 View Questions
    <% end %>
      </td>

      <td>

        <%= link_to edit_paper_path(id: paper.id),'data-original-title':'Detail', class: 'cutom_tootltip pull-right detail-btn' do %>
          Edit Paper
        <% end %>
      </td>

  <% end %>
  </tr>
  <% end %>
  <% end %>
  </tbody>

</table>

app/views/papers/new.html.erb
 <style>
   .col-md-12{
       max-width: 95%;
   }
   .form-inline{
       margin-top: 2%;
       margin-bottom: 20%;
   }
 </style>
  <%#= form_for @paper, url: {controller: "papers", action: "create"} do |f| %>
    <%= nested_form_for @paper,url: {controller: "papers", action: "create"}, method: :post, html: {class: "form-inline",autocomplete:"off",id:"paper_form"} do |f| %>
    <!--    , html:{id: :agentform, onsubmit:"disableButton('agentform','submit_edit_button1')"}-->

   <div class="abcd">
    <div class="col-md-12">
      <div class="row">
        <div class="form-group col-md-4">
          <label for="id">Paper Time</label>
          <input type="text" name='paper[time]' class="form-control">

        </div>
      </div>
      <div class="row">
        <div class="form-group col-md-4">
          <label for="id">Paper Title</label>
          <input type="text" name='paper[subject]' class="form-control">

        </div>
        <div class="form-group col-md-4">
          <label for="id">Question</label>
          <input type="text" name='questions[0][name]' class="form-control">
        </div>
        <div class="form-group col-md-4">
          <label for="id">Option A</label>
          <input type="text" name='multiple_choices[0][option_a]' class="form-control">
        </div>

      </div>


    </div>
    <div class="col-md-12" s>
      <div class="row">
        <div class="form-group col-md-4">
          <label for="id">Option B</label>
          <input type="text" name='multiple_choices[0][option_b]' class="form-control">

        </div>
        <div class="form-group col-md-4">
          <label for="id">Option C</label>
          <input type="text" name='multiple_choices[0][option_c]' class="form-control">
        </div>
        <div class="form-group col-md-4">
          <label for="id">Option D</label>
          <input type="text" name='multiple_choices[0][option_d]' class="form-control">
        </div>

      </div>


    </div>
    <div class="col-md-12" s>
      <div class="row">
        <div class="form-group col-md-4">
          <label for="id">Option E</label>
          <input type="text" name='multiple_choices[0][option_e]' class="form-control">

        </div>
        <div class="form-group col-md-4">
          <label for="id">Correct Option</label>
          <input type="text" name='multiple_choices[0][correct_option]' class="form-control">
        </div>
      </div>


    </div>

<!--<div class="col-md-12">-->



</div>
<div class="row">
  <div class="col-md-12">
    <span id="more_question">Add More Question +</span><br>
<!--  </div>-->
</div>
<!-- </div>-->
   <br>
   <br>
<!--   <div class="row">-->
     <div class="col-md-12">
     <%= submit_tag "Create" , class:'btn btn-primary' %>
     </div>
      </div>
<% end %>



  <script>


      var counter=0
      $('#more_question').on('click',function () {
          debugger
//           document.getElementById('my_file'+counter).click();
          counter=counter+1
          if(counter!=0){
              // $('.abcd').append(' <input type="text" name="paper[subject]['+counter+']"><br>'+
              //     ' <input type="text" name="questions[name]['+counter+']"><br>'+
              // ' <input type="text" name="multiple_choices[option_a]['+counter+']"><br>' +
              // '    <input type="text" name="multiple_choices[option_b]['+counter+']"><br> ' +
              // '   <input type="text" name="multiple_choices[option_c]['+counter+']"><br>' +
              // '   <input type="text" name="multiple_choices[option_d]['+counter+']"><br> ' +
              // '   <input type="text" name="multiple_choices[option_e]['+counter+']"><br> '+
              // '   <input type="text" name="multiple_choices[correct_option]['+counter+']"><br>')




              $('.abcd').append('<div class="col-md-12"><div class="row"> '+
                  ' <div class="form-group col-md-4"> <label for="id">Question '+counter+'</label> <input type="text" name="questions['+counter+'][name]"> </div> <div class="form-group col-md-4"> <label for="id">Option A</label> <input type="text" name="multiple_choices['+counter+'][option_a]" class="form-control"> </div> <div class="form-group col-md-4"><label for="id">Option B</label> <input type="text" name="multiple_choices['+counter+'][option_b]" class="form-control"></div> </div>   </div> ' +
                  '<div class="col-md-12"><div class="row">  '+
                  ' <div class="form-group col-md-4"> <label for="id">Option C</label> <input type="text" name="multiple_choices['+counter+'][option_c]" class="form-control"> </div> <div class="form-group col-md-4"> <label for="id">Option D</label> <input type="text" name="multiple_choices['+counter+'][option_d]" class="form-control"> </div>  <div class="form-group col-md-4"><label for="id">Option E</label> <input type="text" name="multiple_choices['+counter+'][option_e]" class="form-control"></div> </div>   </div> '+
                  '<div class="col-md-12"><div class="row"> '+
                  ' <div class="form-group col-md-4"> <label for="id">Correct Option</label> <input type="text" name="multiple_choices['+counter+'][correct_option]" class="form-control"> </div>  </div>   </div> ');
          }

      });
  </script>

app/views/papers/solve_paper.html.erb
<style>
  .countdown {
      position: fixed;
    top: 0;
    left: 0;
    font-size: 142px;
    width: 100%;
    margin-left: 72%;
    margin-top: 20px;
    }
</style>
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
<%= form_tag submit_paper_papers_path, method: :post, id: "paper_form", remote: true do %>
  <div class="row">
    <%= csrf_meta_tags %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="hidden" name="user_id" value="<%= current_user.id %>">
    <input type="hidden" name="paper_id" value="<%= @paper.try(:id) %>">
    <input type="hidden" id="paper_time" value="<%= @paper.try(:time) %>">
    <% @paper.questions.each_with_index do |q,id| %>
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-6 col-xs-12">
      <div>
        <label class="label--account">Question # <%= id+1 %></label><br>
        <label class="label--account"><%= q.name %> ?</label><br>
        <div class="radio">
          <label><input type="radio" name="question_<%=q.id %>[answer]" value="<%=q.multiple_choice.option_a %>" >  <%= q.multiple_choice.option_a %></label>
        </div>
        <div class="radio">
          <label><input type="radio" name="question_<%=q.id %>[answer]"  value="<%=q.multiple_choice.option_b %>">  <%= q.multiple_choice.option_b %></label>
        </div>
        <div class="radio disabled">
          <label><input type="radio" name="question_<%=q.id%>[answer]"  value="<%=q.multiple_choice.option_c %>">  <%= q.multiple_choice.option_c %></label>
        </div>
        <div class="radio disabled">
          <label><input type="radio" name="question_<%=q.id %>[answer]"  value="<%=q.multiple_choice.option_d %>">  <%= q.multiple_choice.option_d %></label>
        </div>
        <div class="radio disabled">
          <label><input type="radio" name="question_<%=q.id %>[answer]"  value="<%=q.multiple_choice.option_e %>">  <%= q.multiple_choice.option_e %></label>
        </div>
        <%#= select_tag :location_id, options_for_select([[@location.business_name, @location.id]]), {id: "check_location_id",class: 'form-control m-time-bootstrap-select m-bootstrap-select m-bootstrap-select--pill  m_selectpicker reason-dd-1',title: @location.business_name, required: true} %>
        <div class="m--space-10"></div>
      </div>
    </div>
      <% end %>
    <input type="submit" class="btn btn-primary">
  </div>

<% end %>
</div>
  <div class="col-md-2">    <span class="countdown"></span>
  </div>
</div>
<script>
    $(document).ready(function () {
        window.onload=function(){
            // window.setTimeout("redirect()", 5000);
            // OR
            window.setTimeout(function() { redirect(); }, 2000);
        };

        function redirect() {
            // $( "#check_form" ).submit();

            // document.cartCheckout.submit();
        }
        // var minutes = 1, seconds = 59;
        // jQuery(function(){
        //     $("#countdown").html(minutes + ":" + seconds);
        //     var count = setInterval(function(){ if(parseInt(minutes) < 0) { clearInterval(count); } else {jQuery("span.countdown").html(minutes + ":" + seconds); if(seconds == 0) { minutes--; if(minutes < 10) minutes = "0"+minutes; seconds = 59;} seconds--; if(seconds < 10) minutes = "0"+seconds;} }, 1000);
        // })
        if($('#paper_time').val()!=undefined && $('#paper_time').val()!=''){
            var time = $('#paper_time').val();

        }
        else
        {
           var time = "30:00";

        }
        var timer2 = time;
        var interval = setInterval(function() {


            var timer = timer2.split(':');
            //by parsing integer, I avoid all extra string processing
            var minutes = parseInt(timer[0], 10);
            var seconds = parseInt(timer[1], 10);
            --seconds;
            minutes = (seconds < 0) ? --minutes : minutes;
            if (minutes < 0) clearInterval(interval);
            seconds = (seconds < 0) ? 59 : seconds;
            seconds = (seconds < 10) ? '0' + seconds : seconds;
            //minutes = (minutes < 10) ?  minutes : minutes;
            $('.countdown').html(minutes + ':' + seconds);

            if(minutes==0 && seconds =='00'){
                $( "#paper_form" ).submit()
                // alert('time Up')

            }
            timer2 = minutes + ':' + seconds;
        }, 1000);
    })
</script>

app/views/papers/view_questions.html.erb
<div class="container">
  <% @paper.try(:questions).each do |question| %>
    <div class="row">
      <p>   <span class="font-weight-bold">Question: </span><%=question.name %></p><br>
    </div>
    <div class="row">
      <p>
        <span class="font-weight-bold">Correct Option: </span>
        <%=question.try(:multiple_choice).try(:correct_option) %>
      </p><br>
    </div>
  <% end %>

</div>